# Generated by Django 5.0.1 on 2024-01-29 12:13

import django.contrib.auth.models
import django.db.models.deletion
import phonenumber_field.modelfields
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_alter_user_email'),
        ('main', '0002_otm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=50, null=True, verbose_name='Full name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=user.models.image_path)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Telefon raqam')),
                ('role', models.IntegerField(choices=[(0, 'Jismoniy shaxs'), (1, 'Yuridik shaxs')], default=0, verbose_name='Shaxs')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('tolov_summasi', models.IntegerField(blank=True, null=True, verbose_name='Homiylik Summasi')),
                ('holat', models.IntegerField(choices=[(0, 'Yangi'), (1, 'Moderatsiyada'), (2, 'Tasdiqlangan'), (3, 'Bekor qilingan')], default=0)),
                ('tashkilot_nomi', models.CharField(blank=True, max_length=255, null=True)),
                ('sarflangan_summa', models.IntegerField(blank=True, null=True)),
                ('tolov_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tolovturi')),
            ],
            options={
                'verbose_name': 'Homiy',
                'verbose_name_plural': 'Homiylar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=50)),
                ('talabalik_turi', models.IntegerField(choices=[(0, 'Bakalavr'), (1, 'Magistratura')], default=0)),
                ('kontrakt_miqdori', models.IntegerField()),
                ('ajratilgan_summa', models.IntegerField(blank=True, null=True)),
                ('homiy', models.ManyToManyField(to='user.homiy')),
                ('otm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.otm')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
