# Generated by Django 5.0.1 on 2024-01-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_homiy_date_created_remove_homiy_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homiy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
