# Generated by Django 5.0.1 on 2024-01-29 05:36

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_email'),
        ('main', '0002_otm'),
        ('user', '0003_homiy_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=50)),
                ('talabalik_turi', models.IntegerField(choices=[(0, 'Bakalavr'), (1, 'Magistratura')], default=0)),
                ('kontrakt_miqdori', models.IntegerField()),
                ('ajratilgan_summa', models.IntegerField(blank=True, null=True)),
                ('homiy', models.ManyToManyField(to='user.homiy')),
                ('otm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.otm')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
