# Generated by Django 5.0.1 on 2024-01-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_homiy_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiy',
            name='role',
            field=models.IntegerField(choices=[(0, 'Jismoniy shaxs'), (1, 'Yuridik shaxs')], default=0, verbose_name='Shaxs'),
        ),
    ]
